# https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml/

# anywhere with [] needs to be filled
service: [SERVICE NAME]
provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2
  profile:
    ${self:custom.profiles.${opt:stage, self:provider.stage, 'dev'}}
    # these are global env variable
  environment:
    PGDB: ${self:custom.secrets.${opt:stage, self:provider.stage}.dbname}
    PGHOST: ${self:custom.secrets.${opt:stage, self:provider.stage}.host}
    PGPASS: ${self:custom.secrets.${opt:stage, self:provider.stage}.password}
    PGUSER: ${self:custom.secrets.${opt:stage, self:provider.stage}.username}
custom:
  secrets: ${ssm:/aws/reference/secretsmanager/[secret_name]~true}
  defaultStage: dev
  # not sure how this works in CI still need to figure out
  profiles:
    dev: symply-dev
    production: symply-production

package:
  individually: true

functions:
  example:
    handler: src/services/index.main
